### ISSUE TITLE
Command 'todoist.sync' not found

### ISSUE THREAD

**Issue by aadilayub** [spoon611/code-with-todoist#15]
Hi, I just installed this extension a few minutes ago, and added my API token. Whenever I press the sync button in the sidebar I get the error in the title

![image](https://user-images.githubusercontent.com/31581044/95410372-3910f600-093d-11eb-9cde-aac58647fb07.png)

**Comment by ChrArendt** [comment]
The same thing happened for me on MacOS Catalina, I also just installed the addon and get the same error after putting my API token.

**Comment by spoon611** [comment]
@aadilayub @ChrArendt This should be fixed in the latest version v0.4.3

**Comment by ChrArendt** [comment]
> @aadilayub @ChrArendt This should be fixed in the latest version v0.4.3

It's working now for me, thank you :)
