### ISSUE TITLE
Lower the supported VSCode Version

### ISSUE THREAD

**Issue by nchursin** [spoon611/code-with-todoist#18]
**Is your feature request related to a problem? Please describe.**
We have a really restricted env and we cannot use the latest VSCode versions. Current version we have is 1.44. Will you extension functionally work on 1.44? Could you please lower the supported version?

**Describe the solution you'd like**
Lower supported VSCode version to 1.44

**Comment by spoon611** [comment]
Hey! The latest version of the extension v0.5.1 supports vscode v1.44.0 onwards.

**Comment by nchursin** [comment]
Thanks!
