### ISSUE TITLE
Incorrect ordering of sub tasks

### ISSUE THREAD

**Issue by arnold-parge** [spoon611/code-with-todoist#3]
![image](https://user-images.githubusercontent.com/37010276/86519000-f29a8f80-be53-11ea-8940-ff0bb8538e31.png)

The to-do **task** has sub-to-dos in it:

- work on logout
- create modal
- remove the title

These should appear under tasks, but it is appearing in the end.

**Comment by deitry** [comment]
https://github.com/spoon611/code-with-todoist/pull/1 may fix this

**Comment by spoon611** [comment]
@deitry's changes are included in the latest updated version.
@arnold-parge Is the issue still persisting?

**Comment by corderop** [comment]
> @arnold-parge Is the issue still persisting?

Not for me, the order are displayed correct in v0.2.1

**Comment by corderop** [comment]
Working for subtasks but not for task for me
