### ISSUE TITLE
Sub-tasks not hiding when are maked as done

### ISSUE THREAD

**Issue by corderop** [spoon611/code-with-todoist#5]
**Steps**:

1. I've installed the extension
2. Put my API token
3. Get the tasks properly
4. Get the subtasks of a task properly (it hides the subtasks that has already marked as done)
5. Mark a subtask as done
6. The subtask is marked in todoist but it's not hid
7. Subtask doesn't disappear with reloads

![](https://i.ibb.co/Jr91syX/Screenshot-20200825-131643.png)
![](https://i.ibb.co/cLWStkt/Screenshot-20200825-131709.png)

PD: Great job, I will help, if I have free time

**Comment by corderop** [comment]
I was researching a little bit about it. It's a feature of Todoist API. When a task is closed, it won't be shown in active task anymore, but when a subtask is closed, it will be shown as an active task, but marked as completed. I propose to cross out completed subtasks to difference them to the not completed ones.

**Comment by corderop** [comment]
Other choice it's not to show the completed tasks

**Comment by spoon611** [comment]
I think its better to not show the completed tasks.
I will approve #9 

Thanks for your contribution
